### ISSUE TITLE
加一些示例图会更好 :)

### ISSUE THREAD

**Issue by potoo0** [shijieqin/flatfish#2]
:)

**Comment by potoo0** [comment]
还有另一个问题，我没发现配置中需要配置 supervisor 的端口、账户密码等。这样能使用吗？

**Comment by shijieqin** [comment]
supervisor的端口 账户 密码配置需要在前端配置
![image](https://user-images.githubusercontent.com/29157728/57994455-c86efc80-7aef-11e9-8c2f-838d47a2c5e3.png)
supervisor的program name格式为**环境名-模块名-num**，程序会按照这个格式去分类。

**Comment by shijieqin** [comment]
功能目前比较简单，后面会完善的，多谢提出的意见。

**Comment by potoo0** [comment]
哇，大佬回复的好快，有点激动....
好吧，原来是这样，我 ssh 连接的树莓派，电脑访问不到树莓派的 127.0.0.1
这个开发的 ip和端口在哪里修改呢？我只用过 flask，没接触 django。

还有一个问题，地址支持子文件夹吗？例如 www.host.com/supervisor。

**Comment by shijieqin** [comment]
访问hostname/supervisor/node/   即可。
可以使用manage.py runserver 0.0.0.0:18000 的方式来修改监听ip和端口

**Comment by potoo0** [comment]
好的，谢谢。
我在子系统上测试。发现节点显示“Connected”，但看不到进程，点击连接后第n个节点只会弹窗n，也没有其他效果，我看了 前端源码，发现单击 “连接” 按钮并没有发送请求。
是我哪里使用不当吗？麻烦你有时间了帮我看下。我把这个问题发布一个新的 issue 吧。
节点 “连接” 无效果: #4

**Comment by potoo0** [comment]
#4

**Comment by shijieqin** [comment]
连接按钮暂时没有实现相应功能，页面刷新时会自动连接。节点显示Connected，说明已经连接.
