### ISSUE TITLE
节点 “连接” 无效果

### ISSUE THREAD

**Issue by potoo0** [shijieqin/flatfish#4]
1. 初始进入页面，节点就会显示“Connected”，但看不到进程
2. 点击连接后第n个节点只会弹窗n，也没有其他效果，我看了 前端源码，发现单击 “连接” 按钮并没有发送请求。
是我哪里使用不当吗？麻烦你有时间了帮我看下，谢谢。

**Comment by shijieqin** [comment]
节点显示Connected，说明已经连接。连接按钮暂时没做功能，页面刷新时会自动测试连接。
看不到进程的话，看下你的用户是否为超级管理员。

**Comment by potoo0** [comment]
我都使用 sudo 运行，还是获取不到进程，起初我以为是无法获取到未启动的进程，于是我写了两个测试的进行并启动，发现仍然无法获取到进程。我发现 `supervisor/node/detail/test/processes.json` 返回的数据是空的 json。

**Comment by shijieqin** [comment]
奥 我说的是你登录flatfish的用户是否是管理员用户，因为有权限管理，如果不是管理员用户是需要单独授权的。

**Comment by potoo0** [comment]
登陆的是第三步 `python manage.py createsuperuser` 中创建的用户

**Comment by shijieqin** [comment]
supervisor的program name格式是否为**环境名-模块名-num**

**Comment by potoo0** [comment]
举个例子，可以吗？麻烦你了

**Comment by shijieqin** [comment]
![image](https://user-images.githubusercontent.com/29157728/58011442-d5f2a980-7b24-11e9-9de8-7b0b8cfae19b.png)

**Comment by potoo0** [comment]
好的，有效了。谢谢你啦。还可以**弹窗显示日志，支持移动端页面**，非常强大了。

**Comment by potoo0** [comment]
我感觉你的这个比其他的好用多了，我把相关的 supervisor WebUI 的都试了个编，要么不支持显示日志(multivisor)，要么不支持移动端(supervisord-monitor)，要么不支持用户认证(cesi, multivisor)。建议你把 readme.md 补充完全，功能列出来，会很受欢迎，也会有遇到来一起的 contributors.

**Comment by shijieqin** [comment]
好的 谢谢，我找时间完善一下readme.md，之前因为功能不全，比如好多页面404，权限管理目前只能通过admin页面去管理，所以没想着完善，今天因为你，我有了动力，回去完善的。

**Comment by shijieqin** [comment]
对了，权限管理，需要在admin页面先创建用户组，再创建权限，创建权限时关联用户组，节点，环境和模块，然后创建用户加入用户组即可。

**Comment by potoo0** [comment]
我简单学了下flask，有时间也想了解下django，我想把这整个监控项目的地址放到子文件夹下，如www.host.com/monitorPR/...。这样服务器也能在同一域名同一端口下挂网页等自己其他服务(内网穿透每个端口都要钱…所以能省端口最好了)。这个地址子文件夹功能你有时间可以考虑下，在supervisor官方repo里也有很多人提出这个新功能。

我是做了个监控系统，用 supervisor 远程控制摄像头的启动与停止。而网站里还放了博客，在线监控等服务。由于自带的web对手机页面不友好，以及不支持进程分组，无跳转显示日志。花了一整天试了数十个webUI。终于找到你这里，最完美的:)。

**Comment by shijieqin** [comment]
对了，问一下，你对我采取的这种格式化program名字，自动分组的形式与通过配置的形式实现分组有什么意见

**Comment by potoo0** [comment]
em... 分组的话，supervisor 中本身就支持 [[group:x] Section Settings](http://supervisord.org/configuration.html#group-x-section-settings)。不过这里使用自己的规则也可以，效果是一样的。
要说意见的话，可能我有强迫症吧，感觉在 子进程名中出现非变量命名规则的中划线感觉有点难受，可以的话改成下划线。`env-pr-num` --> `env_pr_num`。:)

**Comment by shijieqin** [comment]
因为我是根据env和module自动生成program名字的，_可能会出现env和module中，所以才用了-

**Comment by potoo0** [comment]
哦哦，好吧。也不影响使用，现在就好。把url跳转完善下就完美了。

**Comment by shijieqin** [comment]
好的 有时间就完善，还有什么建议 尽管提

**Comment by potoo0** [comment]
好的，大佬。:)
